#!/bin/bash

#----------------------------------------------------------
#-- HACK: Borders
#----------------------------------------------------------

# INFO: Color converter link = https://convertingcolors.com/

options=(
	style=round
	width=4.0
	hidpi=on
	# active_color=0xFF55DFE0
	# "active_color=gradient(top_left=0xFFFF9B3F,bottom_right=0xFF54B3DF)"
	# "active_color=gradient(top_left=0xFF617D64,bottom_right=0xFFDACE49)"
	"active_color=gradient(top_left=0xFFF7768E,bottom_right=0xFFBB9AF7)"
	inactive_color=0xFF737373
)

borders "${options[@]}"
