#!/bin/sh

source "$CONFIG_DIR/colors.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=top \
	height=30 \
	blur_radius=30 \
	color=$TRANSPARENT \
	sticky=off \
	y_offset=8 \
	padding_left=15 \
	padding_right=15

##### Changing Defaults #####
sketchybar --default icon.font="MesloLGL Nerd Font:Bold:13.0" \
	icon.color=$FG_COLOR \
	label.font="MesloLGL Nerd Font:Bold:13.0" \
	label.color=$FG_COLOR \
	background.color=$BG_COLOR \
	background.corner_radius=7 \
	background.height=30 \
	padding_left=5 \
	padding_right=5 \
	label.padding_left=4 \
	label.padding_right=10 \
	icon.padding_left=10 \
	icon.padding_right=4
#
# INFO: Workspaces
#
source $ITEM_DIR/workspaces.sh

#
# INFO: Front app
#
source $ITEM_DIR/front_app.sh

##### Adding Right Items #####
sketchybar --add item clock right \
	--set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
	padding_right=0 \
	--add item volume right \
	--set volume script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change \
	--add item battery right \
	--set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
	--subscribe battery system_woke power_source_change

sketchybar --add item toggler left \
	--set toggler drawing=off \
	updates=on \
	script="$PLUGIN_DIR/toggle.sh" \
	--subscribe toggler front_app_switched

##### Force all scripts to run the first time (never do this in a script) #####

sketchybar --update
